In [14]:
import numpy as np
import regex as re
from collections import Counter 

In [15]:
corpus = 'red pink pink blue blue yellow ORANGE BLUE BLUE PINK' # 🌈

In [16]:
def process_corpus(corpus) :
    corpus_lower = corpus.lower()
    return re.findall(r'\w+', corpus_lower)

In [17]:
def dictionary(corpus):
    words = process_corpus(corpus)
    word_dic = {}
    for word in words:
        word_dic[word] = word_dic.get(word,0)+1
    counts_b = Counter(word_dic)
    return(len(words),counts_b)

In [18]:
def probability(word,len_words,words_dic):
    return words_dic[word]/len_words

In [29]:
def minimum_edit_distance(word1,word2, del_cost=1, ins_cost=1, repl_cost=2):
    edit_table = np.zeros((len(word1)+1,len(word2)+1))
    for i in range(len(word1)+1):
        edit_table[i][0] = i
    for i in range(len(word2)+1):
        edit_table[0][i] = i
    for i in range(1,len(word1)+1):
        for j in range(1,len(word2)+1):
            op_del = edit_table[i-1][j] + del_cost
            op_ins = edit_table[i][j-1] + ins_cost
            op_repl = edit_table[i-1][j-1]
            if word1[i-1] != word2[j-1]:
                op_repl += repl_cost
            else:
                op_repl+= 0
            edit_table[i][j]=np.min((op_del,op_ins, op_repl))
    return edit_table


In [31]:
print(minimum_edit_distance("money","monkey"))

[[0. 1. 2. 3. 4. 5. 6.]
 [1. 0. 1. 2. 3. 4. 5.]
 [2. 1. 0. 1. 2. 3. 4.]
 [3. 2. 1. 0. 1. 2. 3.]
 [4. 3. 2. 1. 2. 1. 2.]
 [5. 4. 3. 2. 3. 2. 1.]]
